# Generated by Django 5.2.6 on 2025-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
